# Generated by Django 5.1 on 2024-09-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_hiring_portfolio_portfolioimage_post_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='maxPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='minPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.post'),
        ),
    ]
